### ISSUE TITLE
Backporting HAL FDCAN from STM32H7RS

### ISSUE THREAD

**Issue by carlo-dev-git** [STMicroelectronics/stm32h7xx-hal-driver#93]
After a comparison of the FDCAN driver code between the STM32H7 and STM32H7RS, it seems to me that some functions of the STM32H7 series could be improved. Specifically:

* Initialization - `HAL_FDCAN_Init()`

`assert_param(IS_FDCAN_ALL_INSTANCE(hfdcan->Instance));` should be done before this row:
``` c
  if (hfdcan->Instance == FDCAN1)
  {
    hfdcan->ttcan = (TTCAN_TypeDef *)((uint32_t)hfdcan->Instance + 0x100U);
  }
```

* Replace raw numbers with some `#defines` (in .c and .h):
```c
#define SRAMCAN_FLS_NBR                 (128U)         /* Max. Filter List Standard Number      */
#define SRAMCAN_FLE_NBR                  (64U)         /* Max. Filter List Extended Number      */
  (etc.)

  (...)
  assert_param(IS_FDCAN_MAX_VALUE(hfdcan->Init.StdFiltersNbr, SRAMCAN_FLS_NBR));
  assert_param(IS_FDCAN_MAX_VALUE(hfdcan->Init.ExtFiltersNbr, SRAMCAN_FLE_NBR));
  (etc.)

// FDCAN_FilterTypeDef
  uint32_t FilterIndex;      /*!< Specifies the filter which will be initialized.
                                  This parameter must be a number between:
                                   - 0 and (SRAMCAN_FLS_NBR-1), if IdType is FDCAN_STANDARD_ID
                                   - 0 and (SRAMCAN_FLE_NBR-1), if IdType is FDCAN_EXTENDED_ID */

// FDCAN_RxHeaderTypeDef
  uint32_t FilterIndex;           /*!< Specifies the index of matching Rx acceptance filter element.
                                       This parameter must be a number between:
                                        - 0 and (SRAMCAN_FLS_NBR-1), if IdType is FDCAN_STANDARD_ID
                                        - 0 and (SRAMCAN_FLE_NBR-1), if IdType is FDCAN_EXTENDED_ID
                                       When the frame is a Non-Filter matching frame, this parameter
                                       is unused.                                                        */

// FDCAN_HpMsgStatusTypeDef
  uint32_t FilterIndex;    /*!< Specifies the index of matching filter element.
                                This parameter can be a number between:
                                - 0 and (SRAMCAN_FLS_NBR-1), if FilterList is 0 (Standard)
                                - 0 and (SRAMCAN_FLE_NBR-1), if FilterList is 1 (Extended) */
```

* Check `HAL_FDCAN_ConfigFilter()` when `StdFiltersNbr = 0`:

```c
STM32H7
  assert_param(IS_FDCAN_MAX_VALUE(sFilterConfig->FilterIndex, (hfdcan->Init.StdFiltersNbr - 1U)));

STM32H7RS
  assert_param(IS_FDCAN_MAX_VALUE((sFilterConfig->FilterIndex + 1U), hfdcan->Init.StdFiltersNbr));
```
 
* Some timeout functions for STM32H7 use the `FDCAN_TIMEOUT_COUNT  (50U)` value but in STM32H7RS still use `FDCAN_TIMEOUT_VALUE  (10U)`

* Fix typo `FDCAN_CalcultateRamBlockAddresses()` -> `FDCAN_CalculateRamBlockAddresses()`

**Comment by KRASTM** [comment]
Fixed in Commit: https://github.com/STMicroelectronics/stm32h7xx-hal-driver/commit/c022efb12c558b9faaf097e2049d5eb8a9eaa974

**Comment by carlo-dev-git** [comment]
Thank you for your fix but I think some little updates are still missing:

```c
[line 1894]
- assert_param(IS_FDCAN_MAX_VALUE(sFilterConfig->FilterIndex, (hfdcan->Init.ExtFiltersNbr - 1U)));
+ assert_param(IS_FDCAN_MAX_VALUE((sFilterConfig->FilterIndex + 1U), hfdcan->Init.ExtFiltersNbr));
```
and
```c
[In Private define section]
+ #define SRAMCAN_FLS_SIZE            ( 1U * 4U)         /* Filter Standard Element Size in bytes */
+ #define SRAMCAN_FLE_SIZE            ( 2U * 4U)         /* Filter Extended Element Size in bytes */

[line 1886]
- FilterAddress = (uint32_t *)(hfdcan->msgRam.StandardFilterSA + (sFilterConfig->FilterIndex * 4U));
+ FilterAddress = (uint32_t *)(hfdcan->msgRam.StandardFilterSA + (sFilterConfig->FilterIndex * SRAMCAN_FLS_SIZE));

[line 1916]
- FilterAddress = (uint32_t *)(hfdcan->msgRam.ExtendedFilterSA + (sFilterConfig->FilterIndex * 4U * 2U));
+ FilterAddress = (uint32_t *)(hfdcan->msgRam.ExtendedFilterSA + (sFilterConfig->FilterIndex * SRAMCAN_FLE_SIZE));
```
